config/routes.rb
Rails.application.routes.draw do
  resources :loriots
  resources :sensor_data do
    collection do
      post "uplink"
    end
  end
  post "uplink" => "sensor_data#uplink"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loriot.rb
class Loriot < ApplicationRecord
  validates_presence_of :raw_data
end

app/models/sensor_datum.rb
class SensorDatum < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/loriots_controller.rb
class LoriotsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def index
    @loriots = Loriot.all
  end

  def new
  end

  def create
    if request.format.json?
      @loriot = Loriot.new({
        raw_data: request.raw_post
      })
    elsif request.format.html?
      @loriot = Loriot.new(loriot_params)
    end

    respond_to do |format|
      if @loriot.save
        format.html { redirect_to loriots_path, notice: "Loriot created!" }
        format.json { render json: { "status": "OK" } }
      else
        format.html { render :new }
        format.json { render json: { "error": @loriot.errors.full_messages } }
      end
    end
  end

  def destroy
    @loriot = Loriot.find(params[:id])

    @loriot.destroy
    redirect_to loriots_path, notice: "Loriot deleted!"
  end

  private

    def loriot_params
      params.require(:loriot).permit(:raw_data)
    end
end

app/controllers/sensor_data_controller.rb
class SensorDataController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:uplink]

  def index
    @sensor_data = SensorDatum.all
  end

  def new
  end

  def create
    @datum = SensorDatum.new(data_params)

    if @datum.save
      redirect_to sensor_data_path, notice: 'Sensor datum created!'
    else
      render :new
    end
  end

  def destroy
    @datum = SensorDatum.find(params[:id])

    @datum.destroy
    redirect_to sensor_data_path, notice: 'Sensor datum destroyed!'
  end

  def uplink
    payload = Hash.from_xml(request.raw_post)["DevEUI_uplink"]["payload_hex"]
    @datum = SensorDatum.new(
      dev_eui: params[:LrnDevEui], port: params[:LrnFPort],
      info: params[:LrnInfos], payload: payload)
    @datum.save
    
    respond_to do |format|
      format.xml { render xml: "OK" }
    end
  end

  private
    def data_params
      params.require(:sensor_datum).permit(:dev_eui, :port, :info, :payload)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loriots_helper.rb
module LoriotsHelper
end

app/helpers/sensor_data_helper.rb
module SensorDataHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vineyard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/loriots/index.html.erb
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>raw_data</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @loriots.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= item.raw_data %></td>
      <td><%= link_to "Delete", loriot_path(item), method: :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<hr>
<%= link_to "New", new_loriot_path %>

app/views/loriots/new.html.erb
<%= form_for Loriot.new do |f| %>
  <%= f.label :raw_data %>
  <%= f.text_area :raw_data %>

  <%= f.submit "Create" %>
<% end %>

app/views/sensor_data/index.html.erb
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>dev_eui</th>
      <th>port</th>
      <th>info</th>
      <th>payload</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @sensor_data.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= item.dev_eui %></td>
      <td><%= item.port %></td>
      <td><%= item.info %></td>
      <td><%= item.payload %></td>
      <td><%= link_to "Delete", sensor_datum_path(item), method: :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "New", new_sensor_datum_path %>

app/views/sensor_data/new.html.erb
<%= form_for SensorDatum.new do |f| %>
  <%= f.label :dev_eui %>
  <%= f.text_field :dev_eui %>

  <%= f.label :port %>
  <%= f.number_field :port %>

  <%= f.label :info %>
  <%= f.text_field :info %>

  <%= f.label :payload %>
  <%= f.text_field :payload %>

  <%= f.submit "Create" %>
<% end %>